### PR TITLE
fix: adjust type of meta to never in order to override it with a specific type

### PR DESCRIPTION
**Pull request by ckaeslin**
I would improve the developer experience if we could override the type for meta.
This is only possible if never would be used as type for meta.

```
class OrganisationMemberMeta {
  organisation!: Organisation;
}

export default setSeederFactory(
  OrganisationMember,
  (faker, meta: OrganisationMemberMeta) => {
    const member = new OrganisationMember();
    member.organisation = meta.organisation;
    return member;
  }
);
```

### CODE REVIEW

**Comment by tada5hi** [comment]
@ckaeslin i think `never` was the wrong type you were looking for, because nothing is castable to anything.

**Comment by ckaeslin** [comment]
@tada5hi yes, you're right it doesn't work. I'll try to find another solution.

**Comment by ckaeslin** [comment]
I've made another try and extended it with a Meta type which is by default set to unknown to keep the current functionality.

**Comment by tada5hi** [comment]
@ckaeslin i like that approach, looking good :thumbsup:

**Comment by tada5hi** [comment]
Thank you for your contribution :tada:

**Pull request merged**
